[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["application*", "config*", "core*", "infrastructure*"]


[project]
name = "travel_expense_tracker"
version = "0.1.0"
